<?= $this->doctype() ?>

<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('{APP_NAME}')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
    </head>
    <body>

        <?= $this->content ?>

        <?= $this->inlineScript() ?>

    </body>
</html>
